<b> <center> NumPy (NUMerical PYthon) </center> <b>

In [1]:
import numpy as np
array_01 = np.array([1,2,5,4,4,5,8])
print(array_01)

[1 2 5 4 4 5 8]


In [2]:
array_zeros = np.zeros((2,2))
print(array_zeros)

[[0. 0.]
 [0. 0.]]


In [3]:
array_ones = np.ones((3,3))
array_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [4]:
array_empty = np.empty((2,3))
array_empty

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np_arange = np.arange(12)
np_arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
np_arange.reshape((3,4)) #arranges the array in the given matrix

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
np_linspace = np.linspace(1,10,11) # linespaced array, 11 equally spaced numbers between 1 and 10
np_linspace

array([ 1. ,  1.9,  2.8,  3.7,  4.6,  5.5,  6.4,  7.3,  8.2,  9.1, 10. ])

In [8]:
oneD_array = np.arange(15)  # One Dimensional Array
print(oneD_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [9]:
twoD_array = oneD_array.reshape(5,3) # Two Dimensional array
print(twoD_array)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [10]:
# Three Dimensional Array
threeD_array = np.arange(27).reshape(3,3,3)
print(threeD_array)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [11]:
type(np)

module

<i><b>Classes and Attributes of ndarray</i></b><br><br>
<p><b>ndarray.ndim</b>
    number of axis or dimension of the array
<br><b>ndarray.shape</b>
    describes the structure of the array, n rows and m columns, results a tuple     of (n,m)
<br><b>ndarray.size</b>
    number of elements present in the array, rows*columns
<br><b>ndarray.dtype</b>
    object that describes the type of elements in the array, 
    numpy also provides its own datatype (numpy.int32 | numpy.int16  | numpy.float64)
    or use specified python datatypes</p>

In [12]:
np_city = np.array(['NYC', 'LA', 'Boston'])
np_city.ndim # .ndim attribute is used here to find the dimension of the array

1

In [13]:
np_city2d = np.array([['NYC', 'LA', 'Boston'],[1,2,3]])
print("Dimensions of the 'np_city2d' array are " + str(np_city2d.ndim))


Dimensions of the 'np_city2d' array are 2


In [14]:
np_city.shape # .shape attribute is used here to find the rows and columns of the array,
              # here, 3 columns and rank 1, as only one row 

(3,)

In [15]:
rows, columns = np_city2d.shape
print("Rows are {} & Columns are {}".format(rows,columns))


Rows are 2 & Columns are 3


In [16]:
np_city.size # .size attribute is used to determine the number of elements

3

In [17]:
np_city2d.size # 2 rows & 3 columns makes 6 elements

6

In [18]:
np_city.dtype # here, U means unicode string

dtype('<U6')

In [19]:
np_city2d.dtype # 6 is the largest length of an element present in the array

dtype('<U6')

<b><i>Types of DataTypes in NumPy and Key Letters</b></i><br>
i - integer<br>
b - boolean<br>
u - unsigned integer<br>
f - float<br>
c - complex float<br>
m - timedelta<br>
M - datetime<br>
O - object<br>
S - string<br>
U - unicode string<br>
V - fixed chunk of memory for other type ( void )

<i><b>Basic Operations on NumPy Array</i></b><br>
Mathematical Operations<br>
Logical Operations<br>
Comparison Operstions

<br><b> MATHEMATICAL OPERATIONS </b>

In [20]:
first_trial = np.array([10, 15, 17, 26])
second_trial = np.array([12, 11, 21, 24])

In [21]:
# ADDITION
trial_add = first_trial + second_trial # Vector Addition OR Element Wise Addition
trial_add
#np.add(25,15)

array([22, 26, 38, 50])

In [22]:
# SUBTRACTION
trial_sub = first_trial - second_trial
trial_sub
#np.subtract(15,10)

array([-2,  4, -4,  2])

In [23]:
# MULTIPLICATION
np_daily_wage = np.array([2,3,4,5,6])*10
print(np_daily_wage)
mul = first_trial*second_trial
print(mul)

[20 30 40 50 60]
[120 165 357 624]


<br><b>COMPARISION OPERATIONS</b>

In [24]:
np_weekly_hrs = np.array([23,41,55,47,38])
np_weekly_hrs[np_weekly_hrs>40] # > < >= <= !=

array([41, 55, 47])

<br><b>LOGICAL OPERATIONS</b>

In [25]:
np.logical_and(np_weekly_hrs>20,np_weekly_hrs<50)

array([ True,  True, False,  True,  True])

In [26]:
np.logical_not(np_weekly_hrs>35)

array([ True, False, False, False, False])

<br><br><b>ACCESSING ARRAY ELEMENTS</b>
<br><br>
<b>Indexing</b> 

In [27]:
runner_trials = np.array([
    [10, 15, 17, 26],
    [12, 11, 21, 24]
])

In [28]:
first_trial = runner_trials[0] #axis 0
first_trial

array([10, 15, 17, 26])

In [29]:
second_trial = runner_trials[1] #axis 1
second_trial

array([12, 11, 21, 24])

In [30]:
first_runner_first_trial = runner_trials[0][0]  # rows,colunn [0,0]
first_runner_first_trial

10

In [31]:
first_runner_second_trial = runner_trials[1,0] 
first_runner_second_trial

12

In [32]:
first_runner_all_trials = runner_trials[:,0] # use ':' to select all the rows
first_runner_all_trials

array([10, 12])

<br><b>Slicing</b>

In [33]:
runner_trials.shape

(2, 4)

In [34]:
two_runner_trial_data = runner_trials[:,1:3]
two_runner_trial_data

array([[15, 17],
       [11, 21]])

In above code, all rows are being selected and then sliced from 1:3,<br>
that is 2nd and 3rd elements of every row

<br><b>Iteration</b>

In [35]:
for iterate_var in runner_trials:
    print(iterate_var)

[10 15 17 26]
[12 11 21 24]


In [36]:
for iterate_var in two_runner_trial_data:
    print(iterate_var)

[15 17]
[11 21]


<br><b>Indexing with Boolean Arrays</b> 

In [37]:
test_scores = np.array([
    [83,71,57,63],
    [54,68,81,45]
])

In [38]:
passing_scores = test_scores>60
passing_scores

array([[ True,  True, False,  True],
       [False,  True,  True, False]])

Above code snippet sets and checks a condition (Boolean result) 

In [39]:
test_scores[passing_scores]

array([83, 71, 63, 68, 81])

Send 'passing scores' as an argument to 'test scores' object for valuable information

<br><b> UNIVERSAL FUNCTIONS </b>

In [40]:
np_sqrt = np.sqrt([2,4,6,9]) # To perform sqrt of the array elements
np_sqrt

array([1.41421356, 2.        , 2.44948974, 3.        ])

In [41]:
np.cos(0) # To perform cosine function on the elements 

1.0

In [42]:
np.cos([0,1,2,3])

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 ])

In [43]:
from numpy import pi

In [44]:
np.sin(pi/2)

1.0

In [45]:
np.floor([1.2,1.5,1.6,0.2,2.5,2.8,0,-0.1,-0.6,-1.2,-1.8]) # Performs floor, returns largest integer value of the array elements

array([ 1.,  1.,  1.,  0.,  2.,  2.,  0., -1., -1., -2., -2.])

In [46]:
np.exp([0,1,5]) # Returns e^x, where x is the array element

array([  1.        ,   2.71828183, 148.4131591 ])

In [47]:
np.eye(6) # Identity Matrix

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [48]:
np.random.rand(4,3) # Random distribution between 0 and 1

array([[0.6590647 , 0.81679024, 0.07970597],
       [0.80973272, 0.74617605, 0.44834073],
       [0.21964094, 0.58247678, 0.39778173],
       [0.50844772, 0.09512562, 0.84440141]])

In [49]:
np.random.randn(8) # Standard Normal Distribution

array([-0.08713656, -0.63036801,  0.19595777, -0.68498584,  0.21315735,
       -2.12341509, -0.79824668, -0.11522849])

In [50]:
np.random.randn(5,3)

array([[-0.85618076,  0.41279317, -1.53652994],
       [-0.77731493,  0.01601922,  0.08720528],
       [ 0.37426389,  0.98365884,  1.81340174],
       [ 1.46527866, -1.3803831 ,  0.87599499],
       [-0.8350581 ,  0.88924629,  0.46405241]])

In [51]:
np.random.randint(0,101,10) # 10 Random integers between 0 and 101

array([25, 83, 71,  4, 47, 91, 77, 41, 36, 99])

In [52]:
np.random.randint(0,101,(4,5)) # A martrix with 4x5 random elements lying between 0 and 101

array([[58, 58, 20, 22, 31],
       [62,  6, 60,  4,  9],
       [54, 39, 59, 94, 83],
       [69, 20, 47,  1, 44]])

In [53]:
np.random.seed(42) # same set of random numbers 
np.random.rand(6)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
       0.15599452])

In [54]:
np.random.seed(42) 
np.random.rand(6)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
       0.15599452])

In [55]:
np.random.seed(101)
np.random.rand(6)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166, 0.68527698,
       0.83389686])

In [56]:
ran_arr = np.random.randint(0,101,10)

In [57]:
ran_arr

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

In [58]:
ran_arr.max() # Maximum valued element, min for minimum

93

In [59]:
ran_arr.argmax() # Index 

8